import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from './components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className + " flex w-full min-h-screen items-center text-center justify-center flex-col gap-2"}>
        <Navbar />
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}

